In [1]:
import numpy as np

In [18]:
W1 = (np.arange(1, 13)/10).reshape((3, 4))
print(W1)

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [19]:
W2 = (np.arange(1, 4)/10).reshape((1, 3))
print(W2)

[[0.1 0.2 0.3]]


In [20]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [13]:
sigmoid(0)

0.5

In [21]:
sigmoid(W1)

array([[0.52497919, 0.549834  , 0.57444252, 0.59868766],
       [0.62245933, 0.64565631, 0.66818777, 0.68997448],
       [0.7109495 , 0.73105858, 0.75026011, 0.76852478]])

In [27]:
x = [1, .02, .03, .04]

In [28]:
sigmoid(W1 @ x)

array([0.53220535, 0.63760865, 0.73125515])

In [29]:
W2 @ sigmoid(W1 @ x)

array([0.40011881])