In [2]:
import numpy as np

In [4]:
x = np.array([1, .02, .03, .04])
w1_1 = np.array([.1, .2, .3, .4])
w2_1 = np.array([.5, .6, .7, .8])
w3_1 = np.array([.9, 1.0, 1.1, 1.2])
w1_2 = np.array([.1, .2, .3])
print(w1_1)

[0.1 0.2 0.3 0.4]


In [5]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [8]:
sigmoid(np.array([1, 2]))

array([0.73105858, 0.88079708])

In [11]:
a0 = x
a1_1 = sigmoid(np.dot(w1_1, a0))
a2_1 = sigmoid(np.dot(w2_1, a0))
a3_1 = sigmoid(np.dot(w3_1, a0))

In [12]:
print(a1_1, a2_1, a3_1)

0.5322053516104134 0.637608652621925 0.7312551451284902


In [13]:
a1 = np.array([a1_1, a2_1, a3_1])
a1

array([0.53220535, 0.63760865, 0.73125515])

In [15]:
a1_2 = sigmoid(np.dot(w1_2, a1))
a1_2

0.5987162049704826

In [16]:
W1 = np.array([w1_1, w2_1, w3_1])

In [17]:
W1

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2]])

In [19]:
sigmoid(W1 @ a0)

array([0.53220535, 0.63760865, 0.73125515])