In [135]:
import numpy as np


In [136]:
xarray1 = np.arange(0, 3, .1)
xarray2 = np.arange(-1, 2, .1)
print(xarray1, xarray2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9] [-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1 -0.   0.1  0.2  0.3
  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7
  1.8  1.9]


In [137]:
yarray = (xarray1*xarray2 - 2*xarray1 + 1 > 0).astype(int)

In [138]:
yarray

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1])

In [139]:
X_train = np.hstack([ np.ones((len(xarray1), 1)), np.reshape(xarray1, (-1, 1)) , np.reshape(xarray2, (-1, 1)) ] )
#X_train = np.hstack([ np.reshape(xarray, (-1, 1))+1, np.reshape(xarray, (-1, 1)) ] )

In [140]:
np.set_printoptions(suppress=True)
print(X_train)

[[ 1.   0.  -1. ]
 [ 1.   0.1 -0.9]
 [ 1.   0.2 -0.8]
 [ 1.   0.3 -0.7]
 [ 1.   0.4 -0.6]
 [ 1.   0.5 -0.5]
 [ 1.   0.6 -0.4]
 [ 1.   0.7 -0.3]
 [ 1.   0.8 -0.2]
 [ 1.   0.9 -0.1]
 [ 1.   1.  -0. ]
 [ 1.   1.1  0.1]
 [ 1.   1.2  0.2]
 [ 1.   1.3  0.3]
 [ 1.   1.4  0.4]
 [ 1.   1.5  0.5]
 [ 1.   1.6  0.6]
 [ 1.   1.7  0.7]
 [ 1.   1.8  0.8]
 [ 1.   1.9  0.9]
 [ 1.   2.   1. ]
 [ 1.   2.1  1.1]
 [ 1.   2.2  1.2]
 [ 1.   2.3  1.3]
 [ 1.   2.4  1.4]
 [ 1.   2.5  1.5]
 [ 1.   2.6  1.6]
 [ 1.   2.7  1.7]
 [ 1.   2.8  1.8]
 [ 1.   2.9  1.9]]


In [141]:
y_train = yarray

In [142]:
print(y_train)

[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]


In [143]:
print(X_train.shape, y_train.shape)

(30, 3) (30,)


In [144]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [145]:
#input layer = one input (x1) plus bias x0
#hidden layer = 2 nodes, x1 and x2, plus bias x0

from sklearn.neural_network import MLPClassifier, MLPRegressor
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                 hidden_layer_sizes=(2), random_state=1, activation='logistic')
clf.fit(X_train[:, 1:], y_train)
#clf.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=1e-05, hidden_layer_sizes=2,
              random_state=1, solver='lbfgs')

In [146]:
print(clf.coefs_)
print(clf.intercepts_)

[array([[-4.80206981, 29.29122937],
       [32.36618305, 24.15338641]]), array([[ 26.72093158],
       [-19.50466398]])]
[array([-41.0987312 ,   4.57365195]), array([8.45312541])]


In [147]:
clf.loss_

0.0006865896251668326

In [148]:
clf.predict(X_train[:, 1:])  # predict first 5 values in X

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1])

In [149]:
y_train[0:5]

array([1, 1, 1, 1, 0])

In [150]:
W1 = np.array([[-5.83749417, 1.61468679 ],[-0.45701456, 2.2893793 ]])

In [151]:
print(X_train[0])
W1 @ X_train[0]

[ 1.  0. -1.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [47]:
a0 = X_train[5]
print(a0)
a1 = sigmoid(W1 @ a0)
print(a1)
a1 = np.insert(a1, 0, 1)
print(a1)

[ 1.   0.5 -0.5]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [48]:
W2 = np.array([2.62995857, 10.49068236, -4.41164907])

In [44]:
a2 = sigmoid(W2 @ a1)
print(a2)

NameError: name 'a1' is not defined

In [152]:
### START HERE

# Network will have 2 inputs.   (not counting bias)  LAYER 0
# Middle/hidden will have 2 nodes.  (not counting bias)  LAYER 1
# output will have 1 node (not counting bias).  LAYER 2

# 2 layers total, (with 1 input layer=layer 0).  numbered 0-2

# So W1 is dimensions 2 (from hidden layer) by 2 (from input layer), but input is actually 
# 3 inputs because of bias.  so W1 will be 2x3. (2 rows, 3 cols)

W1 = np.random.rand(2, 3)

# W2 is dimensions 1 (from output) by 2 (from hidden), but add extra column for bias.
# So W2 is 1 by 3.

W2 = np.random.rand(1, 3)

print(W1.shape)
print(W2.shape)

(2, 3)
(1, 3)


In [153]:
def compute_z_vector(W, input_vector):
    return W @ input_vector

def compute_activation_vector(z_vector):
    return sigmoid(z_vector)

def augment_vector(v):
    return np.insert(v, 0, 1)

In [154]:
augment_vector(np.array([1, 2, 3]))

array([1, 1, 2, 3])

In [171]:
def forward_prop(all_W, one_input):
    # we assume one_input doesn't have the 1 in front.
    activations = []
    z_vectors = [None]  # no z0, so put this in here as a placeholder
    inputs = [None]
    
    # set a0
    activations.append(one_input)
    
    # for each layer, compute z, compute activation:
    for layer in range(1, len(all_W)):
        print("In layer", layer)
        
        # get activation of previous layer
        activation_prev_layer = activations[layer-1]
        print("Activation of prev layer", layer-1, "is", activation_prev_layer)
        
        # augment the output of previous layer with a 1
        inputs.append(augment_vector(activation_prev_layer))
        print("Input to this layer is", inputs[layer])
        
        # get W matrix
        W = all_W[layer]
        print("Using W of shape", W.shape)
        
        # compute z
        z_this_layer = compute_z_vector(W, inputs[layer])
        print("z is", z_this_layer)
        z_vectors.append(z_this_layer)
        
        # compute activation
        activation_this_layer = compute_activation_vector(z_this_layer)
        print("activation is", activation_this_layer)
        activations.append(activation_this_layer)
    
    return inputs, z_vectors, activations
    

In [172]:
forward_prop([None, W1, W2], X_train[0, 1:])

In layer 1
Activation of prev layer 0 is [ 0. -1.]
Input to this layer is [ 1.  0. -1.]
Using W of shape (2, 3)
z is [ 0.55185398 -0.63296395]
activation is [0.63456562 0.34683878]
In layer 2
Activation of prev layer 1 is [0.63456562 0.34683878]
Input to this layer is [1.         0.63456562 0.34683878]
Using W of shape (1, 3)
z is [1.43252744]
activation is [0.80729482]


([None, array([ 1.,  0., -1.]), array([1.        , 0.63456562, 0.34683878])],
 [None, array([ 0.55185398, -0.63296395]), array([1.43252744])],
 [array([ 0., -1.]), array([0.63456562, 0.34683878]), array([0.80729482])])

In [179]:
def compute_cross_entropy_one_example(y, yhat):
    return -y*np.log(yhat) - (1-y)*np.log(1 - yhat)

def cross_entropy_derivative(y, yhat):
    return (yhat - y)/(yhat * (1-y))

def compute_mse_one_example(y, yhat):
    return .5 * (yhat - y) ** 2

def mse_derivative(y, yhat):
    return (yhat - y)

In [180]:
example_x = X_train[0, 1:]
example_y = y_train[0]
inputs, z, a = forward_prop([None, W1, W2], example_x)
print("activation is", a[-1])
example_yhat = a[-1]

print("cost is", compute_cost_one_example(example_y, example_yhat))

In layer 1
Activation of prev layer 0 is [ 0. -1.]
Input to this layer is [ 1.  0. -1.]
Using W of shape (2, 3)
z is [ 0.55185398 -0.63296395]
activation is [0.63456562 0.34683878]
In layer 2
Activation of prev layer 1 is [0.63456562 0.34683878]
Input to this layer is [1.         0.63456562 0.34683878]
Using W of shape (1, 3)
z is [1.43252744]
activation is [0.80729482]
activation is [0.80729482]
cost is [0.21406636]


In [211]:
loss_fn = compute_mse_one_example
deriv_loss_fn = mse_derivative

def deriv_activation_fn(z):
    return sigmoid(z) * (1-sigmoid(z))

def backprop(all_W, y, yhat, inputs, z_vectors, activations):
    num_layers = len(all_W)-1
    dC_dz = [None] * (num_layers+1)  # 0 through L, 0 will be ignored
    dC_dz[0] = None
    dC_dW = [None] * (num_layers+1)  # 0 through L, 0 will be ignored
    dC_dW[0] = None
    #dC_dz = np.zeros((num_layers),)  # 0 through L, 0 will be ignored
    
    # redo:
    deltas = [None] * (num_layers+1)
    loss_derivs = [None] * (num_layers+1)
    activation_derivs = [None] * (num_layers+1)
    
    print("number of layers is", num_layers)
    #print("dC/dz", dC_dz)
    #print("dC/dW", dC_dW)
    
    # init last layer things
    #dC_dz[num_layers] = activations[num_layers] - y
    #print("dC/dz", dC_dz)
    #print("SSS",dC_dz[num_layers],np.transpose(activations[num_layers - 1]))
    #dC_dW[num_layers] = np.dot(dC_dz[num_layers], np.transpose(activations[num_layers - 1]))
    #print("dC/dW", dC_dW)
    
    # init last layer things
    loss_derivs[num_layers] = deriv_loss_fn(y, activations[num_layers])   #y, yhat
    print("y, yhat", y, yhat)
    activation_derivs[num_layers] = deriv_activation_fn(z_vectors[num_layers])
    deltas[num_layers] = loss_derivs[num_layers] * activation_derivs[num_layers]
    print("delta at output", deltas)
    
    for layer in range(len(all_W)-2, 0, -1):
        print("backprop at layer", layer)
        this_delta = activation_derivs[num_layers] @ deltas[layer+1]
    
    

In [212]:
example_x = X_train[0, 1:]
example_y = y_train[0]
inputs, z, a = forward_prop([None, W1, W2], example_x)
print("activation. is", a[-1])
example_yhat = a[-1]

compute_cost_one_example(example_y, example_yhat)

backprop([None, W1, W2], example_y, example_yhat, inputs, z, a)

In layer 1
Activation of prev layer 0 is [ 0. -1.]
Input to this layer is [ 1.  0. -1.]
Using W of shape (2, 3)
z is [ 0.55185398 -0.63296395]
activation is [0.63456562 0.34683878]
In layer 2
Activation of prev layer 1 is [0.63456562 0.34683878]
Input to this layer is [1.         0.63456562 0.34683878]
Using W of shape (1, 3)
z is [1.43252744]
activation is [0.80729482]
activation. is [0.80729482]
number of layers is 2
y, yhat 1 [0.80729482]
delta at output [None, None, array([-0.02997913])]
backprop at layer 1


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [185]:
np.array([3, 4]) * np.array([3, 4])

array([ 9, 16])

In [213]:
def f(x, y, z):
    return (x+y) * z

In [214]:
f(-2, 5, -4)

-12

In [216]:
f(-2, 6, -4)

-16