In [1]:
import numpy as np


In [19]:
xarray = np.arange(0, 3, .1)
print(xarray)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [20]:
yarray = xarray*xarray - 3*xarray + 1

In [70]:
yarray

array([ 1.  ,  0.71,  0.44,  0.19, -0.04, -0.25, -0.44, -0.61, -0.76,
       -0.89, -1.  , -1.09, -1.16, -1.21, -1.24, -1.25, -1.24, -1.21,
       -1.16, -1.09, -1.  , -0.89, -0.76, -0.61, -0.44, -0.25, -0.04,
        0.19,  0.44,  0.71])

In [71]:
X_train = np.hstack([ np.ones((len(xarray), 1)), np.reshape(xarray, (-1, 1)) ] )
#X_train = np.hstack([ np.reshape(xarray, (-1, 1))+1, np.reshape(xarray, (-1, 1)) ] )

In [72]:
print(X_train)

[[1.  0. ]
 [1.  0.1]
 [1.  0.2]
 [1.  0.3]
 [1.  0.4]
 [1.  0.5]
 [1.  0.6]
 [1.  0.7]
 [1.  0.8]
 [1.  0.9]
 [1.  1. ]
 [1.  1.1]
 [1.  1.2]
 [1.  1.3]
 [1.  1.4]
 [1.  1.5]
 [1.  1.6]
 [1.  1.7]
 [1.  1.8]
 [1.  1.9]
 [1.  2. ]
 [1.  2.1]
 [1.  2.2]
 [1.  2.3]
 [1.  2.4]
 [1.  2.5]
 [1.  2.6]
 [1.  2.7]
 [1.  2.8]
 [1.  2.9]]


In [84]:
y_train = yarray

In [85]:
print(y_train)

[ 1.    0.71  0.44  0.19 -0.04 -0.25 -0.44 -0.61 -0.76 -0.89 -1.   -1.09
 -1.16 -1.21 -1.24 -1.25 -1.24 -1.21 -1.16 -1.09 -1.   -0.89 -0.76 -0.61
 -0.44 -0.25 -0.04  0.19  0.44  0.71]


In [92]:
print(X_train.shape, y_train.shape)

(30, 2) (30,)


In [93]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [176]:
#input layer = one input (x1) plus bias x0
#hidden layer = 2 nodes, x1 and x2, plus bias x0

from sklearn.neural_network import MLPClassifier, MLPRegressor
clf = MLPRegressor(solver='lbfgs', alpha=1e-5,
                 hidden_layer_sizes=(2), random_state=1, activation='logistic')
clf.fit(X_train[:, 1].reshape(-1, 1), y_train)
#clf.fit(X_train, y_train)

MLPRegressor(activation='logistic', alpha=1e-05, hidden_layer_sizes=2,
             random_state=1, solver='lbfgs')

In [177]:
print(clf.coefs_)
print(clf.intercepts_)

[array([[1.61468679, 2.2893793 ]]), array([[10.49068236],
       [-4.41164907]])]
[array([-5.83749417, -0.45701456]), array([2.62995857])]


In [178]:
clf.loss_

0.00021223464802675674

In [179]:
clf.predict(X_train[:, 1][0:5].reshape(-1, 1))  # predict first 5 values in X

array([ 0.95009077,  0.71042813,  0.46526804,  0.22121893, -0.0150863 ])

In [157]:
y_train[0:5]

array([ 1.  ,  0.71,  0.44,  0.19, -0.04])

In [158]:
W1 = np.array([[-5.83749417, 1.61468679 ],[-0.45701456, 2.2893793 ]])

In [159]:
print(X_train[0])
W1 @ X_train[0]

[1. 0.]


array([-5.83749417, -0.45701456])

In [169]:
a0 = X_train[5]
print(a0)
a1 = sigmoid(W1 @ a0)
print(a1)
a1 = np.insert(a1, 0, 1)
print(a1)

[1.  0.5]
[0.00649536 0.66544954]
[1.         0.00649536 0.66544954]


In [170]:
W2 = np.array([2.62995857, 10.49068236, -4.41164907])

In [171]:
a2 = sigmoid(W2 @ a1)
print(a2)

0.4408703537701813
